controller/__init__.py
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask
from config import config_dict

# factory function
def create_app(config_type):
    # Retrieve the configuration subclass according to the type
    config_class = config_dict[config_type]
    app = Flask(__name__)
    app.config.from_object(config_class)

    # register blueprint
    from controller.modules.home import home_blu
    app.register_blueprint(home_blu)
    from controller.modules.user import user_blu
    app.register_blueprint(user_blu)

    return app

controller/modules/home/__init__.py
from flask import Blueprint

# create blueprint
home_blu = Blueprint("home", __name__)

# relate view function with program
from controller.modules.home.views import *

controller/modules/home/views.py
from flask import session, render_template, redirect, url_for, Response
from controller.modules.home import home_blu

from importlib import import_module
import os
from flask import Flask, render_template, Response

import cv2
camera = cv2.VideoCapture('./copy/gonglu3.mp4')
def generate_frames():
    while camera.isOpened():
        success, frame1 = camera.read()
        if not success:
            break
        else:
            ret, buffer = cv2.imencode('.jpg', frame1)
            frame1 = buffer.tobytes()
            print("enter3")
            yield (b'--frame1\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame1 + b'\r\n')  # concat frame one by one and show result


'''import camera driver'''
if os.environ.get('CAMERA'):
    Camera = import_module('camera_' + os.environ['CAMERA']).Camera
else:
    from controller.utils.yolo_deepsort import Camera

# Main page
@home_blu.route('/')
def index():
    username = session.get("username")
    if not username:
        return redirect(url_for("user.login"))
    return render_template("index.html")

def video_stream(camera):
    # 产生video stream
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


# video stream
@home_blu.route('/video_viewer')
def video_viewer():
    username = session.get("username")
    if not username:
        return redirect(url_for("user.login"))
    '''
    return Response(video_stream(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')
    '''
    return Response(video_stream(Camera()), mimetype='multipart/x-mixed-replace; boundary=frame')

controller/modules/user/__init__.py
from flask import Blueprint

# create bluepring
user_blu = Blueprint("user", __name__)

# relate view function and main program
from controller.modules.user.views import *

controller/modules/user/views.py
from flask import session, redirect, url_for, request, render_template, jsonify
from controller.modules.user import user_blu

stopflag = True

# Login
@user_blu.route("/login", methods=["GET", "POST"])
def login():
    username = session.get("username")

    if username:
        #return redirect(url_for("home.index"))
        return redirect(url_for("user.startpage"))

    if request.method == "GET":
        return render_template("login.html")
    # obtain parameter
    username = request.form.get("username")
    password = request.form.get("password")
    # check parameter
    if not all([username, password]):
        return render_template("login.html", errmsg="Lack of Input")

    # validate username and password
    if username == "aaa" and password == "aaa":
        # pass
        session["username"] = username
        #return redirect(url_for("home.index"))
        return redirect(url_for("user.startpage"))

    return render_template("login.html", errmsg="Incorrect Username or Password")

# Startpage
@user_blu.route("/startpage")
def startpage():
    username = session.get("username")
    if not username:
        return redirect(url_for("user.login"))

    print("startpage")
    print("stopflag = true")
    global stopflag
    stopflag = True

    return render_template("startpage.html")

# Logout
@user_blu.route("/logout")
def logout():
    # Delete session
    print("stopflag = true")
    global stopflag
    stopflag = True
    session.pop("username", None)
    # Back to login page
    return redirect(url_for("user.login"))

# Video status
@user_blu.route('/video_status', methods=['POST'])
def video_status():
    username = session.get("username")
    if not username:
        return redirect(url_for("user.login"))

    json = request.get_json()
    status = json['status']

    global stopflag

    if status == "false":
        print("stopflag = false")
        stopflag = False
        return jsonify('stopped!')

    else:
        print("stopflag = true")
        stopflag = True
        return jsonify('started!')

controller/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Surveillance System</title>
    <style>
        body {
            /*background-color: #484856;*/
            background-color: #434343;
        }

        .top .recorder .btn{
            font-size: 20px;
            font-weight:bold;
            color: #515151;
            width: 90px;
            height: 30px;
            border: None;
            border-radius: 1px;
            cursor: pointer;
        }

        .corner {
            border-radius: 1px;
            /*border: 5px solid rgb(0,255,0);*/
            padding: 0px;
            max-width:80%;
            max-height:80vh;
            text-align: center;
        }

        .video-container {
            padding-top: 0.5em;
            justify-content: center;
            text-align: center;
            height:100%;
            /*border: 1px solid black;*/
        }

    </style>
</head>
<body>
<h1 align="center" style="color: #ffffff;">Highway Traffic Video Stream</h1>
<div class="top">
    <div class="recorder" id="recorder" align="center">
        <button id="stop" class="btn">Stop</button>
        <button id="restart" class="btn">Restart</button>
        <button id="logout" class="btn">Logout</button>
        <!--<input type="button" class="btn" value="退出登录"
               onclick="javascript:window.location.href='{{ url_for('user.logout') }}'">-->
        <!--<script type="text/javascript" src="{{ url_for('static', filename='recorder.js') }}"></script>-->
        <script type="text/javascript">
            var buttonStop = document.getElementById("stop");
            var buttonRestart = document.getElementById("restart");
            var buttonLogout = document.getElementById("logout");
            var buttonTest = document.getElementById("test");

            buttonStop.disabled = true
            buttonRestart.disabled = true;
            buttonLogout.disabled = true;

            function sleep(millisecond) {
		        return new Promise(resolve => {
		            setTimeout(() => {
		                resolve()
		            }, millisecond)
		        })
		    }

            async function test() {
		        const start = new Date().getTime();
		        await sleep(5000); // delay
                buttonStop.disabled = false;
		    }

            test()

            buttonStop.onclick = function () {

                var xhr = new XMLHttpRequest();
                xhr.open("POST", "/video_status");
                xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
                xhr.send(JSON.stringify({status: "false"}));

                buttonStop.disabled = true;
                buttonRestart.disabled = false;
                buttonLogout.disabled = false;
            };

            buttonRestart.onclick = function () {
                var xhr = new XMLHttpRequest();
                xhr.open("POST", "/video_status");
                xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
                xhr.send(JSON.stringify({status: "true"}));
                window.location.href="{{ url_for('user.startpage') }}";
            };

            buttonLogout.onclick = function () {
                var xhr = new XMLHttpRequest();
                xhr.open("POST", "/video_status");
                xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
                xhr.send(JSON.stringify({status: "true"}));
                window.location.href="{{ url_for('user.logout') }}";
            };
        </script>
    </div>
</div>
<div class="video-container">
    <img id="video" src="{{ url_for('home.video_viewer') }}" class="corner">
</div>
</body>
</html>

controller/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <link href="../static/css/style.css" rel='stylesheet' type='text/css'/>
    <script src="http://ajax.useso.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
<script>$(document).ready(function (c) {
    $('.close').on('click', function (c) {
        $('.login-form').fadeOut('slow', function (c) {
            $('.login-form').remove();
        });
    });
});
</script>
<!--SIGN UP-->
<h1>Highway Traffic Incident Detection System</h1>
<div class="login-form">
    <div class="clear"></div>
    <div class="avtar">
        <img src="../static/images/avtar.png"/>
    </div>
    <form method="post" action="{{ url_for("user.login") }}">
        <input type="text" class="text" name="username" value="Username" onfocus="this.value = '';"
               onblur="if (this.value == '') {this.value = 'Username';}">
        <div class="key">
            <input type="password" name="password" value="Password" onfocus="this.value = '';"
                   onblur="if (this.value == '') {this.value = 'Password';}">
        </div>
        <div class="signin">
            <input type="submit" value="Login">
            {% if errmsg %} {# check incorrect message #}

                <div class="error_tip" style="display: block;color: red">{{ errmsg }}</div>

            {% endif %}
        </div>
    </form>

</div>
<div class="copy-rights">
    <p> Copyright@2022 </p>
</div>

</body>
</html>

controller/templates/mail.html
<html>
<head></head>
<body>
<table border="0" cellpadding="0" cellspacing="0" width="100%" align="center" id="aaaa" style="border-collapse:collapse; background-color:#1f1f1f;">
	<tbody><tr>
		<td align="center" valign="top" id="Tem_FullBox" style="width:100%; height:100%; padding:10px; box-sizing:border-box;">
			<table border="0" cellpadding="0" cellspacing="0" width="650" class="Tem_Container">
				<tbody>
				<tr>
					<td valign="top" id="aaaaaa" style="background-color:#ffffff;">

						
						<table border="0" cellpadding="0" cellspacing="0" class="dddddd" width="100%" align="center">
							<tbody><tr>
								<td class="bbbbbb" align="center" valign="top">
									<div class="cccccc" id="000000">
										<div class="eeeeee" data-tooltype="image">
											<div class="ffffff">
												<table border="0" cellpadding="0" cellspacing="0" width="100%" class="gggggg" align="center">
													<tbody><tr>
														<td align="center" valign="top">
															<table border="0" cellpadding="0" cellspacing="0" width="100%" class="jjjjjj">
																<tbody><tr>
																	<td align="center" valign="top" class="hhhhhh"><img width="650" class="kkkkkk" src="https://store.heytapimage.com/cdo-portal/feedback/202204/25/cf36c0a165a045214ff6693b12942613.png" style="display:block; width:30% !important; height:auto !important;"></td>
																</tr>
															</tbody></table>
														</td>
													</tr>
												</tbody></table>
											</div>
										</div>
									</div>
								</td>
							</tr>
						</tbody></table>



						<table border="0" cellpadding="0" cellspacing="0" class="dddddd" width="100%" align="center">
							<tbody><tr>
								<td class="bbbbbb px20" align="center" valign="top" style="padding:0 40px;">
									<div class="cccccc" id="111111">
										<div class="eeeeee" data-tooltype="divider">
											<div class="ffffff">
												<table border="0" cellpadding="0" cellspacing="0" width="100%" class="gggggg">
													<tbody><tr>
														<td align="left" valign="top">
															<table border="0" cellpadding="0" cellspacing="0" width="100%">
																<tbody><tr>
																	<td valign="top" class="pppppp" style="padding:20px 0;">
																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="qqqqqq">
																			<tbody><tr>
																				<td class="oooooo" style="border-top:0; height:0; line-height:0; font-size:0;"></td>
																			</tr>
																		</tbody></table>
																	</td>
																</tr>
															</tbody></table>
														</td>
													</tr>
												</tbody></table>
											</div>
										</div>
									</div>
									<div class="cccccc" id="222222">
										<div class="eeeeee" data-tooltype="text">
											<div class="ffffff">
												<table border="0" cellpadding="0" cellspacing="0" width="100%" class="gggggg">
													<tbody><tr>
														<td align="left" valign="top" style="padding:0;">
															<table border="0" cellpadding="0" cellspacing="0" width="100%">
																<tbody><tr>
																	<td valign="top" class="rrrrrr" style="color:#313131; font-family:'Trebuchet MS', Arial; font-size:36px; line-height:1.2; text-align:center; mso-line-height-rule:exactly;"><div class="llllll"><div class="mmmmmm" dir="ltr"><div class="nnnnnn" dir="ltr" contenteditable="true" aria-disabled="false" spellcheck="true">Incident Detected!</div></div></div></td>
																</tr>
															</tbody></table>
														</td>
													</tr>
												</tbody></table>
											</div>
										</div>
									</div>
									<div class="cccccc" id="333333">
										<div class="eeeeee" data-tooltype="image">
											<div class="ffffff">
												<table border="0" cellpadding="0" cellspacing="0" width="100%" class="gggggg" align="center">
													<tbody><tr>
														<td align="center" valign="top" style="padding:10px 0;">
															<table border="0" cellpadding="0" cellspacing="0" width="100%" class="jjjjjj">
																<tbody><tr>
																	<td align="center" valign="top" class="hhhhhh"><img width="570" class="kkkkkk" src="http://edm.focussend.cn/focussend/cust/focussend/ThemeTemplate/images/Weeklyline.png" style="display:block; width:100% !important; height:auto !important;"></td>
																</tr>
															</tbody></table>
														</td>
													</tr>
												</tbody></table>
											</div>
										</div>
									</div>
									<div class="cccccc" id="444444">
										<div class="eeeeee" data-tooltype="text">
											<div class="ffffff">
												<table border="0" cellpadding="0" cellspacing="0" width="100%" class="gggggg">
													<tbody><tr>
														<td align="left" valign="top" style="padding:0;">
															<table border="0" cellpadding="0" cellspacing="0" width="100%">
																<tbody><tr>
																	<td valign="top" class="rrrrrr" style="color:#919191; font-family:'Trebuchet MS', Arial; font-size:14px; line-height:1.6; text-align:center; mso-line-height-rule:exactly;"><div class="llllll"><div class="mmmmmm" dir="ltr"><div class="nnnnnn" dir="ltr" contenteditable="true" aria-disabled="false" spellcheck="true">Please log in to the incident detection system to check</div></div></div></td>
																</tr>
															</tbody></table>
														</td>
													</tr>
												</tbody></table>
											</div>
										</div>
									</div>
									
									<div class="cccccc" id="555555">
										<div class="eeeeee" data-tooltype="divider">
											<div class="ffffff">
												<table border="0" cellpadding="0" cellspacing="0" width="100%" class="gggggg">
													<tbody><tr>
														<td align="left" valign="top">
															<table border="0" cellpadding="0" cellspacing="0" width="100%">
																<tbody><tr>
																	<td valign="top" class="pppppp" style="padding:20px 0;">
																		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="qqqqqq">
																			<tbody><tr>
																				<td class="oooooo" style="border-top:0; height:0; line-height:0; font-size:0;"></td>
																			</tr>
																		</tbody></table>
																	</td>
																</tr>
															</tbody></table>
														</td>
													</tr>
												</tbody></table>
											</div>
										</div>
									</div>
								</td>
							</tr>
						</tbody></table>
					</td>
				</tr>
			</tbody></table>
		</td>
	</tr>
</tbody></table>
</body>
</html>

controller/templates/startpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>startpage</title>
    <link rel="stylesheet" type="text/css" href="../static/css/startpage.css">
</head>
<body>
    <a href="http://192.168.3.50:8866/inference/output">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Recorded
    </a>
    <a href="javascript:window.location.href='{{ url_for('home.index') }}'">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Start
    </a>
    <a href="javascript:window.location.href='{{ url_for('user.logout') }}'">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Logout
    </a>
</body>
</html>